import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query"; import { apiFetch } from "../lib/api"; import type { JobDetail, JobListItem, JobReport, JobSource, JobStatus, ListResponse } from "../lib/types"; import { TERMINAL_JOB_STATUSES } from "../lib/types";
const interval=(q:{state:{data?:{status?:JobStatus}}})=>{const s=q.state.data?.status; return s&&TERMINAL_JOB_STATUSES.includes(s)?false:3000};
export function useJobs(limit=50,offset=0,status?:JobStatus,templateId?:number){const qs=new URLSearchParams({limit:String(limit),offset:String(offset)}); if(status)qs.set("status",status); if(templateId)qs.set("template_id",String(templateId)); return useQuery({queryKey:["jobs",{limit,offset,status,templateId}], queryFn:()=>apiFetch<ListResponse<JobListItem>>(`/api/jobs?${qs}`)})}
export function useJob(id:number,enabled=true){return useQuery({queryKey:["job",id], enabled, queryFn:()=>apiFetch<JobDetail>(`/api/jobs/${id}`), refetchInterval:interval})}
export function useJobReport(id:number,status?:JobStatus){return useQuery({queryKey:["job",id,"report"], queryFn:()=>apiFetch<JobReport>(`/api/jobs/${id}/report`), refetchInterval:status&&TERMINAL_JOB_STATUSES.includes(status)?false:3000})}
export function useJobSource(id:number,enabled:boolean){return useQuery({queryKey:["job",id,"source"], enabled, queryFn:()=>apiFetch<JobSource>(`/api/jobs/${id}/source`)})}
export function useJobSummary(){return useQuery({queryKey:["jobs","summary"], queryFn:()=>apiFetch<{pending_approval:JobListItem[];running:number;last_7_days:Record<string,number>;recent:JobListItem[]}>("/api/jobs/summary")})}
export function useLaunchJob(){const qc=useQueryClient();return useMutation({mutationFn:(body:unknown)=>apiFetch<{id:number;status:string;mode:string}>("/api/jobs",{method:"POST",body:JSON.stringify(body)}),onSuccess:()=>qc.invalidateQueries({queryKey:["jobs"]})})}
export function useRelaunchJob(id:number){const qc=useQueryClient();return useMutation({mutationFn:(body:{hosts:"all"|"failed";mode?:string})=>apiFetch<{id:number;status:string;mode:string}>(`/api/jobs/${id}/relaunch`,{method:"POST",body:JSON.stringify(body)}),onSuccess:()=>qc.invalidateQueries({queryKey:["jobs"]})})}
export function useJobAction(id:number, action:"approve"|"reject"|"cancel"){const qc=useQueryClient();return useMutation({mutationFn:(body?:unknown)=>apiFetch(`/api/jobs/${id}/${action}`,{method:"POST",body:body?JSON.stringify(body):undefined}),onSuccess:()=>{qc.invalidateQueries({queryKey:["jobs"]});qc.invalidateQueries({queryKey:["job",id]});qc.invalidateQueries({queryKey:["pipeline-run"]});}})}
export function useCancelJob(){const qc=useQueryClient();return useMutation({mutationFn:(id:number)=>apiFetch(`/api/jobs/${id}/cancel`,{method:"POST"}),onSuccess:(_d,id)=>{qc.invalidateQueries({queryKey:["jobs"]});qc.invalidateQueries({queryKey:["job",id]});qc.invalidateQueries({queryKey:["pipeline-run"]});}})}
